defaults:
  - data_loader: no_context
  - mlp: two_layer_mlp
  - policy: averaging
  - override hydra/launcher: joblib
  - _self_

main:
  use_wandb: False
  num_splits: 5

wandb:
  entity: Null
  project: Null
  tags: [sanity_checks]
  name: ${policy.name}