name: SLAgg
params:
  seed: 42069
  # dim: will come from main
  batch_size: 50
  lr: 0.001
  weight_decay: 1e-4
  patience: 4
  max_grad_steps: 2000
  testing: False
  # loss_fn_type: will come from mlp
  eval_interval: 50
  print_stuff: False